const array = [
    {
        bill: "One Dollar",
        price: "1.01",
        image: "1",
        tagline: "One Dollar Bill!",
        border: "im",
        currency: "$",
        type: ["presidents only","show all"],
    },
    {
        bill: "Two Dollars",
        price: "2.01",
        image: "2",
        tagline: "Two Dollar Bill!",
        border: "im",
        currency: "$",
        type: ["presidents only","sort by if i could beat the person in a fight","show all"],
    },
    {
        bill: "Five Dollars",
        price: "5.01",
        image: "5",
        tagline: "Five Dollar Bill!",
        border: "im",
        currency: "$",
        type: ["presidents only","show all"],
    },
    {
        bill: "Five Pounds",
        price: "6.30",
        image: "pound",
        tagline: "Five Pounds!",
        border: "im",
        currency: "£",
        type: ["show all"],
    },
    {
        bill: "Ten Dollars",
        price: "10.01",
        image: "10",
        tagline: "Ten Dollar Bill!",
        border: "im",
        currency: "$",
        type: ["show all"],
    },
    {
        bill: "Twenty Dollars",
        price: "20.01",
        image: "20",
        tagline: "Twenty Dollar Bill!",
        border: "im",
        currency: "$",
        type: ["presidents only","sort by if i could beat the person in a fight","show all"],
    },
    {
        bill: "Bass",
        price: "30.01",
        image: "bass",
        tagline: "30 Dollar Bass Pro Shop Gift Card!",
        border: "im",
        currency: "$",
        type: ["sort by if i could beat the person in a fight","show all"],
    },
    {
        bill: "Fifty Dollars",
        price: "50.01",
        image: "50",
        tagline: "Take a Wild Guess",
        border: "im",
        currency: "$",
        type: ["presidents only","sort by if i could beat the person in a fight","find bills over 50 units","show all"],
    },
    {
        bill: "One Hundred Dollars",
        price: "100.01",
        image: "100",
        tagline: "One Hundred Dollar Bill!",
        border: "im",
        currency: "$",
        type: ["find bills over 50 units","show all"],
    },
    {
        bill: "Whalen Dollar",
        price: "101.01",
        image: "whalen",
        tagline: "art in its purest form",
        border: "im",
        currency: "$",
        type: ["highest quality stock","find bills over 50 units","show all"],
    },
    {
        bill: "Thousand Dollar",
        price: "1000.01",
        image: "1000",
        tagline: "Vintage Thousand Dollar Bill!",
        border: "borderlessim",
        currency: "$",
        type: ["presidents only","sort by if i could beat the person in a fight","find bills over 50 units","show all"],
    },
    {
        bill: "Poke Dollar",
        price: "1,000,000.1",
        image: "bike",
        tagline: "Cerulean City Bike Voucher!",
        border: "borderlessim",
        currency: '<img src="d/PokeDollar.jpg">',
        type: ["find bills over 50 units","show all"],
    },
    
]

export {array}