const array = [
    {
        bill: "One Dollar",
        price: "1.01",
        name: "Washington",
        fight: "N",
        president: "Y",
        image: "1",
        tagline: "One Dollar Bill!",
        border: "im",
        currency: "$",
    },
    {
        bill: "Two Dollars",
        price: "2.01",
        name: "Jefferson",
        fight: "Y",
        president: "Y",
        image: "2",
        tagline: "Two Dollar Bill!",
        border: "im",
        currency: "$",
    },
    {
        bill: "Five Dollars",
        price: "5.01",
        name: "Lincoln",
        fight: "N",
        president: "Y",
        image: "5",
        tagline: "Five Dollar Bill!",
        border: "im",
        currency: "$",
    },
    {
        bill: "Five Pounds",
        price: "5.01",
        name: "Elizabeth",
        fight: "N",
        president: "N",
        image: "pound",
        tagline: "Five Pounds!",
        border: "im",
        currency: "£",
    },
    {
        bill: "Ten Dollars",
        price: "10.01",
        name: "Hamilton",
        fight: "N",
        president: "N",
        image: "10",
        tagline: "Ten Dollar Bill!",
        border: "im",
        currency: "$",
    },
    {
        bill: "Twenty Dollars",
        price: "20.01",
        name: "Jackson",
        fight: "Y",
        president: "Y",
        image: "20",
        tagline: "Twenty Dollar Bill!",
        border: "im",
        currency: "$",
    },
    {
        bill: "Bass",
        price: "30.01",
        name: "N",
        fight: "N",
        president: "N",
        image: "bass",
        tagline: "30 Dollar Bass Pro Shop Gift Card!",
        border: "im",
        currency: "$",
    },
    {
        bill: "Fifty Dollars",
        price: "50.01",
        name: "Grant",
        fight: "N",
        president: "Y",
        image: "50",
        tagline: "Take a Wild Guess",
        border: "im",
        currency: "$",
    },
    {
        bill: "One Hundred Dollars",
        price: "100.01",
        name: "Franklin",
        fight: "Y",
        president: "N",
        image: "100",
        tagline: "One Hundred Dollar Bill!",
        border: "im",
        currency: "$",
    },
    {
        bill: "Whalen Dollar",
        price: "101.01",
        name: "Whalen",
        fight: "N",
        president: "N",
        image: "whalen",
        tagline: "art in its purest form",
        border: "im",
        currency: "$",
    },
    {
        bill: "Thousand Dollar",
        price: "1000.01",
        name: "Cleaveland",
        fight: "Y",
        president: "Y",
        image: "1000",
        tagline: "Vintage Thousand Dollar Bill!",
        border: "borderlessim",
        currency: "$",
    },
    {
        bill: "Poke Dollar",
        price: "1,000,001",
        name: "N",
        fight: "N",
        president: "N",
        image: "bike",
        tagline: "Cerulean City Bike Voucher!",
        border: "borderlessim",
        currency: '<img src="d/PokeDollar.jpg">',
    },
    
]

export {array}