const array = [
    {
        bill: "One Dollar",
        price: "1.01",
        name: "Washington",
        fight: "N",
        president: "Y",
        image: "1",
        tagline: "woah!",
    },
    {
        bill: "Two Dollars",
        price: "2.01",
        name: "Jefferson",
        fight: "Y",
        president: "Y",
        image: "2",
        tagline: "woah!",
    },
    {
        bill: "Five Dollars",
        price: "5.01",
        name: "Lincoln",
        fight: "N",
        president: "Y",
        image: "5",
        tagline: "woah!",
    },
    {
        bill: "Five Pounds",
        price: "6.11",
        name: "Elizabeth",
        fight: "N",
        president: "N",
        image: "pound",
        tagline: "woah!",
    },
    {
        bill: "Ten Dollars",
        price: "10.01",
        name: "Hamilton",
        fight: "N",
        president: "N",
        image: "10",
        tagline: "woah!",
    },
    {
        bill: "Twenty Dollars",
        price: "20.01",
        name: "Jackson",
        fight: "Y",
        president: "Y",
        image: "20",
        tagline: "woah!",
    },
    {
        bill: "Bass",
        price: "30.01",
        name: "N",
        fight: "N",
        president: "N",
        image: "bass",
        tagline: "woah!",
    },
    {
        bill: "Fifty Dollars",
        price: "50.01",
        name: "Grant",
        fight: "N",
        president: "Y",
        image: "50",
        tagline: "woah!",
    },
    {
        bill: "One Hundred Dollars",
        price: "100.01",
        name: "Franklin",
        fight: "Y",
        president: "N",
        image: "100",
        tagline: "woah!",
    },
    {
        bill: "Whalen Dollar",
        price: "100.02",
        name: "Whalen",
        fight: "N",
        president: "N",
        image: "whalen",
        tagline: "woah!",
    },
    {
        bill: "Thousand Dollar",
        price: "1000.01",
        name: "Cleaveland",
        fight: "Y",
        president: "Y",
        image: "1000",
        tagline: "woah!",
    },
    {
        bill: "Poke Dollar",
        price: "6,591.23",
        name: "N",
        fight: "N",
        president: "N",
        image: "bike",
        tagline: "woah!",
    },
    
]

export {array}